### ISSUE TITLE
[PiranhaJava] Integrate piranha to our microservice

### ISSUE THREAD

**Issue by cnarsimharaju** [uber/piranha#105]
We are working on integrating piranha to our micro-service. we followed the steps mentioned in the Readme file. We are using [lombok](https://mvnrepository.com/artifact/org.projectlombok/lombok/1.18.16) in our service.  When we ran the build, below error is observed.

**Stack Trace:**

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project qb-billing-service-app: Compilation failure

[ERROR] /Users/ssathyamurthy/dev/qb-billing-service/app/src/main/java/com/intuit/billingcomm/billing/integration/IAMTicketClientIntegration.java:[76,42] error: An unhandled exception was thrown by the Error Prone static analysis plugin.

[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.4.0
[ERROR]      BugPattern: Piranha
[ERROR]      Stack Trace:
[ERROR]      java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCBinary cannot be cast to com.sun.source.tree.ParenthesizedTree
[ERROR]   	at com.uber.piranha.XPFlagCleaner.matchIf(XPFlagCleaner.java:1021)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:655)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:152)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:522)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:152)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:742)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:152)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:550)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:152)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:562)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:152)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[ERROR]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
[ERROR]   	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
[ERROR]   	at com.sun.tools.javac.main.Main.compile(Main.java:302)
[ERROR]   	at com.sun.tools.javac.main.Main.compile(Main.java:162)
[ERROR]   	at com.sun.tools.javac.Main.compile(Main.java:57)
[ERROR]   	at com.sun.tools.javac.Main.main(Main.java:43)
[ERROR] `

**Our Code where this issue in seen**
`@Override
    public @NonNull
    IAMTicket createAndRenewOfflineTicket(@NonNull String realmID) throws IAMTicketClientException {`

**Comment by mkr-plse** [comment]
Can you share the conditional branch (`if`) in this method implementation?

**Comment by sivacoder** [comment]
Surprisingly, there are no branching statements in this method. Complete code is

`   @Override`
`    public @NonNull`
`    IAMTicket createAndRenewOfflineTicket(@NonNull String realmID) throws Exception {`
`            Ticket ticket = new Ticket();`
`        Request request;`
`        try {`
`            request = new Request().build();`
`            Header header = client.getHeader(request);`
`ticket.setTicket(header)`
`        } catch (Exception e) {`
`            throw e;`
`        }`
`        return iamTicket;`
`    }`

**Comment by cnarsimharaju** [comment]
@mkr-plse  It is complaining at the function definition i.e 

`@Override public @NonNull IAMTicket createAndRenewOfflineTicket(@NonNull String realmID) throw`..

**Comment by mkr-plse** [comment]
Looks like a lombok+errorprone related [issue](https://github.com/google/error-prone/issues/690#issuecomment-351304525). Can you try the suggestion there (`-Xep:ParameterName:OFF`) and see whether it resolves the issue?

**Comment by lazaroclapp** [comment]
Lombok modifies the AST in memory during compilation, causing a number of issues when Error Prone tries to associate AST nodes back to the corresponding source code. In this case, it's almost certain that Lombok is adding a conditional to the AST that doesn't exist in the source, and there is something in that conditional that Piranha is trying to report/delete. Unfortunately, since the conditional itself doesn't exist in the code, it can't be reported on or deleted.

In general, there is no reasonable way to make Piranha refactor code that was injected by Lombok. Our best bet would be to:

1) Require `lombok.addLombokGeneratedAnnotation = true` as part to the Lombok configuration
2) Modify Piranha to skip syntactic scopes (e.g. methods, classes), marked as `@lombok.Generated`

That will still sometimes fail to clean up flag usages inside java classes that use Lombok (since Lombok can move user code and nest it inside its own generated structures), but it will avoid an outright compiler crash. Doing any better than that would require encoding knowledge of (potentially many) relevant Lombok transformations inside Piranha.

**Comment by lazaroclapp** [comment]
Can you provide a delombok-ed version of the full compilation unit (i.e. the .java file)?

See [these](https://projectlombok.org/features/delombok) instructions.

**Comment by krmahadevan** [comment]
@lazaroclapp - I have hit this same issue.
Here are some details around my project

My lombok annotated java class 

```java
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Student {

  private boolean isHomeSchooled;
}
```

The delomboked java class that was generated

```java
public class Student {
  private boolean isHomeSchooled;

  @java.lang.SuppressWarnings("all")
  public boolean isHomeSchooled() {
    return this.isHomeSchooled;
  }

  @java.lang.SuppressWarnings("all")
  public void setHomeSchooled(final boolean isHomeSchooled) {
    this.isHomeSchooled = isHomeSchooled;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof Student)) return false;
    final Student other = (Student) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    if (this.isHomeSchooled() != other.isHomeSchooled()) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof Student;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    result = result * PRIME + (this.isHomeSchooled() ? 79 : 97);
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  public java.lang.String toString() {
    return "Student(isHomeSchooled=" + this.isHomeSchooled() + ")";
  }

  @java.lang.SuppressWarnings("all")
  public Student(final boolean isHomeSchooled) {
    this.isHomeSchooled = isHomeSchooled;
  }

  @java.lang.SuppressWarnings("all")
  public Student() {
  }
}
```

Below is how the maven compiler plugin has been configured

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.8.0</version>
	<configuration>
		<source>11</source>
		<target>11</target>
		<encoding>UTF-8</encoding>
		<compilerArgs>
			<arg>-XDcompilePolicy=simple</arg>
			<arg>-Xplugin:ErrorProne
        -Xep:Piranha:WARN
        -XepPatchChecks:Piranha
        -XepPatchLocation:IN_PLACE
        -XepOpt:Piranha:FlagName=${flag}
        -XepOpt:Piranha:IsTreated=${treated}
        -XepOpt:Piranha:Config=src/main/resources/config/properties.json
    </arg>
		</compilerArgs>
		<annotationProcessorPaths>
			<path>
				<groupId>com.uber.piranha</groupId>
				<artifactId>piranha</artifactId>
				<version>0.1.8</version>
			</path>
			<path>
				<groupId>com.google.errorprone</groupId>
				<artifactId>error_prone_core</artifactId>
				<version>2.14.0</version>
			</path>
			<path>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.24</version>
			</path>
		</annotationProcessorPaths>
	</configuration>
</plugin>
```

My dependencies look like below

```xml
  <dependencies>
    <dependency>
      <groupId>org.togglz</groupId>
      <artifactId>togglz-core</artifactId>
      <version>3.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>${lombok.version}</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

Here's how the stacktrace looks like

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project feature_flags: Compilation failure
[ERROR] /Users/krishnamahadevan/githome/playground/feature_flags/src/main/java/com/acme/configs/Student.java:[7,1] An unhandled exception was thrown by the Error Prone static analysis plugin.
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.14.0
[ERROR]      BugPattern: Piranha
[ERROR]      Stack Trace:
[ERROR]      java.lang.ClassCastException: class com.sun.tools.javac.tree.JCTree$JCBinary cannot be cast to class com.sun.source.tree.ParenthesizedTree (com.sun.tools.javac.tree.JCTree$JCBinary and com.sun.source.tree.ParenthesizedTree are in module jdk.compiler of loader 'app')
[ERROR]         at com.uber.piranha.XPFlagCleaner.matchIf(XPFlagCleaner.java:1413)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:653)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:150)
[ERROR]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1433)
[ERROR]         at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
[ERROR]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1032)
[ERROR]         at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
[ERROR]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
[ERROR]         at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
[ERROR]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
[ERROR]         at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]         at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
[ERROR]         at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[ERROR]         at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[ERROR]         at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
[ERROR]         at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
[ERROR]         at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
[ERROR]         at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
[ERROR]         at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by krmahadevan** [comment]
fwiw, the contents of `src/main/resources/config/properties.json` is as below

```json
{
  "methodProperties":
  [
    {
      "methodName": "isActive",
      "flagType": "treated",
      "argumentIndex": 0
    },
    {
      "methodName": "isActive",
      "flagType": "control",
      "argumentIndex": 0
    }
  ],
  "linkURL": "<provide_your_url>",
  "annotations": ["FlagTesting"]
}

```

**Comment by mkr-plse** [comment]
We are pivoting towards [Polyglot](https://github.com/uber/piranha/tree/master/generic) Piranha, which is a common code deletion infrastructure across multiple languages. (cc @ketkarameya)

@krmahadevan Can you try that version?

**Comment by krmahadevan** [comment]
@mkr-plse - I can give it a try. Let me go through the documentation to find out what I need to be doing to adopt it and then give it a try. Oh btw, is there any chance wherein the binaries are pre-built for `piranha` so that I can skip the part of building these binaries ? Or should I just stick to cloning the repo, point to a recent tag, build the binary locally and only then use it? Eventually I would like to take this to a CI and I did read about piranha being used in Uber's CI for auto code deletion (But not sure if its the piranha java that is at work there or is it the generic piranha). Basically trying to avoid code building, because I would have to circulate the instructions to the developers to do this at the local machines (until we are at the CI maturity).

**Comment by ketkarameya** [comment]
Hey @krmahadevan we are planning to release the pre-built binaries for `piranha/generic` soon. :) 
I know it's painful that developers will have to build the binaries now. There are a few more small fixes and cleanups I want to do before I make the binary available :|. My goal is that Piranha will be available as 
1. as a cargo crate  (since `piranha/generic` is developed in Rust)
2. as binaries for different OS

**Comment by krmahadevan** [comment]
@ketkarameya - That's nice 👍 I was dreading that I had to learn the rudiments of rust (Yet another programming language 😄 ).. to be able to build the binary. But good to know that you folks are on top of that as well.

I will give this a shot at my end and see if I can get past my problem. Please bear with me if I keep coming back with some really silly questions until then. The notion of AST and tree-sitter are all new to me and a bit overwhelming as well :) and now have been added to the never ending list of things that I need to still figure out.. :)

Lastly.. this is a fantastic library that you folks have built. I loved the engineering blog that was created for Piranha!! Awesome engineering stuff!!!

**Comment by ketkarameya** [comment]
Feel free to ask us anything related to `tree-sitter`, or even the `rules` for Piranha.  We want improve our documentation too. So feel free if to tell us if you don't understand something there.

**Comment by krmahadevan** [comment]
> Feel free to ask us anything related to `tree-sitter`, or even the `rules` for Piranha. We want improve our documentation too. So feel free if to tell us if you don't understand something there.

Yes sure. Goes without saying. I can try to add some additional details in the `README.md` if I think that would help others use as well via a PR.

**Comment by ketkarameya** [comment]
@krmahadevan I am assuming that your issue was resolved and am closing this issue for now.  Feel free to reopen the issue incase you have any more questions.

**Comment by krmahadevan** [comment]
@ketkarameya - Thanks for following up. I got sidelined at work with other stuff. I will come back with any additional queries on this once we get back to working on the feature flags notion and then using Piranha for auto reversal of obsolete feature flags.
