### ISSUE TITLE
question - what is "implements ExpName"

### ISSUE THREAD

**Issue by avnerbarr** [uber/piranha#109]
I read the article. trying to understand how I am to go about implementing this in code.

In the article you show the flag implementing an interface as follows:

```
public enum RidesExpName implements ExpName {
   RIDES_NEW_FEATURE,
   …
}
```

but I don't see what `ExpName` is or how it is defined

later in code you show checking the feature toggle:

```
if (experiments.isTreated(RIDES_NEW_FEATURE)) {
     // implementation for treatment (on) behavior
} else {
     // implementation for control (off) behavior
}
```

But where is the `experiments` created and how is it defined + passed in?

Can you provide a more complete example that I could follow?

Thanks!

**Comment by mkr-plse** [comment]
While the `implements` case is a use case, there are other ways of defining flags. You can also check the example in code [here](https://github.com/uber/piranha/blob/master/java/sample/src/main/java/com/uber/mylib/MyClass.java). There are a lot more examples in the [tests](https://github.com/uber/piranha/blob/master/java/piranha/src/test/java/com/uber/piranha/XPFlagCleanerTest.java) for other styles of flag definition.

**Comment by ketkarameya** [comment]
Hey! I am closing this issue for now. If you still have questions, feel free to reopen them.
