### ISSUE TITLE
[PiranhaJava] Implement flexible test annotation specification language in configuration

### ISSUE THREAD

**Issue by lazaroclapp** [uber/piranha#115]
This long issue is mostly to clarify my own ideas on how to implement a better test annotation specification in our configuration file, and to document those design decisions for posterity. 

Feel free to comment on it, particularly if you think I am doing something silly (or something that won't work for your - external / non-Uber - use case!), but I don't expect anyone but me to really read this before implementation.

Design might change as I implement this.

**Background:**

PiranhaJava supports marking test methods with annotations, specified by name in our `*.json` configuration file, which indicate that a test depends on a particular value of flag.

See the following example:

```
  @ToggleTesting(treated = TestExperimentName.STALE_FLAG)
  // BUG: Diagnostic contains: Cleans stale XP flags
  public void annotation_test() { ... }
```
(from [here](https://github.com/uber/piranha/blob/master/java/piranha/src/test/resources/com/uber/piranha/XPFlagCleanerPositiveCases.java#L181))

When Piranha analyses that code, if the flag `TestExperimentName.STALE_FLAG` is being cleaned up as "treated", it will simply remove the annotation (which is now redundant, as the value of the flag is always treated). However, if the flag is being set to "control", Piranha will instead delete the whole test, since the annotation indicates that it is testing behavior that will no longer be present/possible in the app.

The structure of the annotation above reflects a series of old annotations used internally at Uber. However, our internal experimentation platform has evolved, and with it, the annotations used. 

More modern annotations look like this (obscuring some of the internal naming conventions):

```
@NewToggleTreated(
  value = "FLAG_NAME_AS_STRING",
  group = "SOME_GROUP_AS_STRING",
  withParams = {@ParamSpecAnnotation(key = "...", value = "..."), ...}
)
```

With a separate annotation to mark flags as control:

```
@NewToggleControl(
  value = "FLAG_NAME_AS_STRING",
)
```

We could just modify PiranhaJava to now assume this later scheme for annotations, but that seems too tied up to whatever we are doing internally and to Uber's experimentation APIs. Ideally, we would like to provide enough configurability at least to be able to specify both the old and new shape of these annotations, since that's bound to allow a lot more flexibility as to which experimentation APIs Piranha supports.

In the extreme, this is the sort of concern to which a plug-in architecture and custom annotation parsers written in Java and loaded up with `@AutoService` might be applied. We have done so for e.g. [NullAway library models](https://github.com/uber/NullAway/wiki/Configuration#library-models). 

However, that's a very heavyweight option, which will not work out of the box for many users without writing custom plug-in code. For the time being, a potentially better option is to encode a small annotation specification language into our `.json` config file. 

**Proposed design:**

Currently, annotation names are specified in our configuration file as:

```
  "annotations": [
    "ToggleTesting"
  ]
```

Instead of a list of strings, `annotations` could be a list of dictionaries, with three mandatory properties:

- `name` (the annotation name, e.g. "ToggleTesting" or "NewToggleTreated")
- `flag` (the name of the flag being referenced by the annotation, which can either be a string representing the unchanging name of the flag for this annotation, or, more commonly, an specification of which annotation field will contain the flag when the annotation is used, e.g. `$treated` for our old annotations, `$value` for the new ones)
- `treated` (whether the test is testing the treated or control case. This can be a boolean constant at definition time, e.g. `"false"` for `NewToggleControl`. It can also, again, be a reference to a field of the annotation)

Additionally, we'd want to support an optional `group` field, which is always a reference to the field of the annotation specifying treatment group. This is required to fully decode `@NewToggleTreated`

Besides allowing to specify which annotation fields specify which properties of the flag being used for the test, we wish to be flexible on _how_ the annotation specifies this. You'll notice that `ToggleTesting` gives the flag as a symbol, whereas `NewToggleTreated` and `NewToggleControl` use a string. Our philosophy here is that we should try to auto-detect and parse these cases without needing additional configuration in the `.json` file, to keep configuration from being too verbose (worst case scenario: type information can be read from the annotation definition itself during Error Prone processing).

**Limitations:**

For the time being, we have no plans to parse `NewToggleTreated.withParams`, since this value is not really relevant to cleaning up code. When Piranha cleans up a flag, internally, it replaces all calls to getting its parameters with constant values based on the deployed parameters for the experiment/configuration. Because of this, we cannot easily force the parameters to be different from the test. This might cause some test to break after the flag is cleaned up and the annotation removed, but there is no natural way to automatically fix the test.

**Backwards compatibility:**

For the sake of backward compatibility and existing Piranha deployments, we should allow elements within the `annotations` list in the `.json` file to be either dictionaries (in the new format) or strings. When an entry is just a string like "FooAnnotation", it will just internally be expanded to:

```
  { "name" : "FooAnnotation", "flag" : "$treated", "treated" : "true" }
```

which is equivalent to the current behavior.

**Putting it all together:**

A `properties.json` file supporting all three annotations described in this write-up would end up looking like:

```
{
  "methodProperties": [ ... ],
  "linkURL": "<provide_your_url>",
  "annotations": [
    "ToggleTesting",
    {
        "name" : "NewToggleTreated",
        "flag" : "$value",
        "treated" : "true",
        "group" : "$group"
    },
    {
        "name" : "NewToggleControl",
        "flag" : "$value",
        "treated" : "false"
    }
  ]
}
```

**Comment by mkr-plse** [comment]
Looks reasonable given that the updated spec is similar in style to `methodProperties`.
