### ISSUE TITLE
[PiranhaJava] Remove comments associated with removed enum constants

### ISSUE THREAD

**Issue by tnterdan** [uber/piranha#148]
Currently, Piranha cleans up enum constants using error-prone's `replace()` method, often using an end position adjustment.

error-prone has a public method in the `SuggestedFixes` class: `replaceIncludingComments(TreePath path, String replacement, VisitorState state` that we could use here to also remove any preceding comments.

However, because we use an end position adjustment to remove the trailing enum constant comma/semi-colon, we cannot use the `replaceIncludingComments` method right now.

Suggested ways to fix this:
1. Remove the enum constant at the place in the tree path that includes the comma/semi-colon. Then we won't need the end position adjustment anymore and can use the `replaceIncludingComments` method as is.
2. Add an end position adjustment to an overload of `replaceIncludingComments` in error-prone, and then update piranha to use that version of error-prone
3. Copy the `replaceIncludingComments` method into Piranha and change it to work with the end position adjustment (not recommended)

**Comment by ketkarameya** [comment]
Since the PR corresponding to this issue is merged, I am closing this issue.
