### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by SaezChristopher** [uber/piranha#17]
Amazing tool !
Is the kotlin support is planned ?

**Comment by mkruber** [comment]
Thanks for your feedback. 

Currently, we don't have any concrete plans for kotlin support. Contributions are welcome.

**Comment by msridhar** [comment]
FYI I just saw Facebook's ktfmt project:

https://github.com/facebookincubator/ktfmt

This gives an example of parsing Kotlin code and then re-generating code from an AST.  A similar approach could possibly be used to implement Piranha support for Kotlin.

**Comment by Samhithgb** [comment]
The Kotlin support will be really great!

**Comment by rohankapoor** [comment]
Kotlin support will be really great!

**Comment by SerhiiSolobaievUptech** [comment]
Waiting for Kotlin support 😍

**Comment by Abhijith-net** [comment]
Will be working on this.
cc: @msridhar

**Comment by Samhithgb** [comment]
@Abhijith-net Thanks a lot, that's great news! Any idea about the timeline for this?

**Comment by msridhar** [comment]
Also @Abhijith-net would be interested in knowing what libraries you will use for parsing and rewriting Korlam code

**Comment by Abhijith-net** [comment]
@msridhar Will let you know by this Sunday on the plan. Sorry for delay in response.

**Comment by Samhithgb** [comment]
@Abhijith-net, curious to know if you were able to start on this?

**Comment by rohankapoor** [comment]
Hi team. Is this something in the works? For us, Kotlin support is a must as most of our code has moved to use Kotlin in the past year.

**Comment by mkr-plse** [comment]
This is not in the works currently but may be prioritized in the next few months. fyi @lazaroclapp @rajbarik.

**Comment by ketkarameya** [comment]
@rohankapoor @Abhijith-net  @Samhithgb @SerhiiSolobaievUptech @SaezChristopher We have added some support for Kotlin (it's in the main branch) . :) Please try it out, and we can iterate over it.

**Comment by ketkarameya** [comment]
Closing this issue for now. Let us know, if you have problems using it.
