### ISSUE TITLE
Introduce a `match-only` feature

### ISSUE THREAD

**Issue by ketkarameya** [uber/piranha#207]
Often users (incl. internal users) don't want to perform the actual rewrite, rather they just want a report of the feature flag api usage - file, start-line, start-col, end-line, end-col.  Even better, can we generate a report for all changes (/matches) performed ? Related - issue #26

**Comment by j1nma** [comment]
+1 to this! Thanks for bringing it up!

**Comment by ketkarameya** [comment]
Closing. This is a duplicate of #26 . @j1nma please track #26 for updates.
