### ISSUE TITLE
Rename `rules.constraints` to `rules.exclude`

### ISSUE THREAD

**Issue by ketkarameya** [uber/piranha#229]
Rationale: 
as @lazaroclapp mentioned in one of the [reviews](https://github.com/uber/piranha/pull/225/files/ea753b3e7a7fd7d6890674a0b789d80e61f992b0#r959090037), `exclude` or `filter` is a better term for [this](https://github.com/uber/piranha/blob/master/polyglot/piranha/src/models/rule.rs#L54) attribute than `constraints`, since it is basically a "exclude-filter".
The goal here is straightforward rename [`constraint`]
(https://github.com/uber/piranha/blob/master/src/models/rule.rs#L81) to `filter`.  

This is also a good issue for someone new to rust and wants to familiarize themselves with rust tooling. At a higher level - setup vscode for with rust-analyzer,  trigger rename refactoring and regex-replace.
Check list: 
- [ ] update the field name, getter / setter ... in [rules]
- [ ] rename the file and contents of [constraints.rs](https://github.com/uber/piranha/blob/master/src/models/constraints.rs) to filter.rs and `Constraints` to `Filter` (and so on)
- [ ] Update the code comments, variable names and method names with the pattern (`constraint`(`s`) -> `filter`(`s`), `matcher` -> `enclosing_node` and `queries` -> `not_contains`
- [ ] Update README.md
(https://github.com/uber/piranha/blob/master/polyglot/piranha/src/cleanup_rules/java/rules.toml#L341)

How to check if all is well (locally)?
```
cd piranha
cargo build --no-default-features
cargo test --no-default-features 
maturin develop  ( python3-m env .env; source .env/bin/activate; pip3 install maturin .... look at readme if u get stuck) 
pytest test/test.py
cargo test --no-default-feature -- --include-ignored  # might require over a minute or two
```

**Comment by JamesBondOOO7** [comment]
Hey @ketkarameya!
Is the issue still open?

**Comment by ketkarameya** [comment]
Thanks a lot for offering to contribute. 
Yes, it is open. 
In addition to "tips" in the issue,  I want to add that we don't want to introduce a breaking change. So you could use [this](https://serde.rs/field-attrs.html#alias) to maintain backward compatibility.

**Comment by ketkarameya** [comment]
OW! Also some links are dead in the issue :|  I guess you will have to figure it out from the file name in the link

**Comment by ketkarameya** [comment]
Welcome to Uber OSS and Rust :) 
I had written this issue long time ago, so rethinking about it.


1. Yes, we need to rename that struct. How about renaming `Constraint` to `ExcludeFilter` ? 
2. Yes, `Constraint` struct is used in `Rules` and many more places 
3. we can rename the file to `rule_filter.rs` ? 
4. Adapt `constraints` to `filters` in code comments and documentation. Give it a shot or mark that part it as TODO, and we can take it up as part of of our code review 
5. Lets rename all except one or two? So that we test that our changes are backward compatible. 


Note we follow the fork model for the oss contribution. So you might have to fork this repo, clone your fork, create a new branch, make changes,  and then push it to your fork. From there, you can make a PR for this repository. 

Did you attempt to set up the project with VS code?

**Comment by JamesBondOOO7** [comment]
I have forked the repo and then cloned it and am working on a new branch.

I did set it up on VS code, but can't run `rust-analyser` extension (maybe because this project has various languages involved).

**Comment by ketkarameya** [comment]
Yes. We gotta do something like that. 

VS Code should work out of the box for you. What issue are u facing ? 

Try the below steps: 
1. clone your fork 
2. `cd piranha`
3.  `python3 -m venv .env && source .env/bin/activate`
4. `cargo build` (`--no-default-features` if you are on Mac)

**Comment by ketkarameya** [comment]
I dont see various languages being a problem for setting up VSCode and Rust Analyzer

**Comment by JamesBondOOO7** [comment]
Hey @ketkarameya 

I followed these steps, but my `cargo build` is failing

I am having this error:
```
error: failed to run custom build command for `piranha v0.2.1 (C:\Users\manan\OneDrive\Documents\GitHub\piranha)`

Caused by:
  process didn't exit successfully: `C:\Users\manan\OneDrive\Documents\GitHub\piranha\target\debug\build\piranha-14517ab0b2594efa\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Could not create virtual environment: Error { kind: NotFound, message: "program not found" }', build.rs:24:6
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Also, I had to use this `.env\Scripts\activate` instead of this `source .env/bin/activate` command as my windows isn't supporting the source command.

**Comment by ketkarameya** [comment]
I see.
You might have to retry the steps and tinker with it. 
Do you have`venv` and `rust` installed?  I guess `rust` is installed. 
It's been a while I have worked on a windows machine, but do you think that installation of [these](https://github.com/uber/piranha/blob/master/build.rs) packages might be failing?

Another option would be - 
use Windows subsystem Linux and then work on ur ubuntu machine :)

**Comment by JamesBondOOO7** [comment]
Hey @ketkarameya 

I installed Ubuntu and everything worked smoothly.
I have raised a PR [here](https://github.com/uber/piranha/pull/352)
Could you review it?

On a side note: It was super fun to work on this.
