### ISSUE TITLE
Failing to create scope query 

### ISSUE THREAD

**Issue by Pencilvesterr** [uber/piranha#232]
### Reproducing Error 
For a very simple use case:
```java
package com.some.package;

import com.a.b.c.RolloutFlag;

class SandboxHashFinder {
    static final RolloutFlag FLAG_TO_DELETE = new RolloutFlag("TEST_FF_KEY");
}
```
There is one rule that identifies the feature flag and deletes it, then a second rule containing a query will not find a match, and so not complete. 
```toml
[[rules]]
name = "delete_boolean_flag_declaration_in_class"
query = """(
 (class_declaration
 	name: (identifier)
  	body: (class_body 
     (field_declaration
      declarator: (variable_declarator
       name: (identifier) @boolean_flag_constant
       value: (object_creation_expression
        type: (type_identifier) @constructor
        arguments: (argument_list (
         (string_literal) @argument
        ))
       )
      ) 
    ) @rollout_flag_declaration
  )
 ) 
 (#match? @constructor "RolloutFlag$|BooleanFlag$")
 (#eq? @argument "\\"@flag_key_to_delete\\"")
)"""
replace_node = "rollout_flag_declaration"
replace = ""
groups = ["delete_boolean_flag_constant"]
holes = ["flag_key_to_delete"]

[[rules]]
name = "rule_with_no_match"
query = """(
 (method_invocation
  object: (method_invocation
   name: (_) @first_method_name
   arguments: (argument_list (
    (_) @first_argument
   ))
  )
 ) @method_chain

 (#eq? @first_argument "@boolean_flag_constant")
)"""
replace_node = "method_chain"
replace = "@lamba_function_body"
groups = []
holes = ["boolean_flag_constant"]
```
These rules are connected with a very simple `edges.toml` file:
```toml
[[edges]]
scope = "Global"
from = "delete_boolean_flag_constant"
to = ["rule_with_no_match"]
```

When connected with `scope=Global` or `scope=Parent`, then the first rule completes successfully, and the second rule's query has no match so does not run.

The problem is when the scope of the edge is changed to `scope=Class` or `scope=File`. Then the following error is raised: 
```
thread 'main' panicked at 'Could not create scope query for "File"', src/models/scopes.rs:81:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Probable Error Source
Within `scopes.rs`,  my understanding is that the error is raised when the function `fn get_scope_query(...)`, cannot find a node that matches the scope's matcher in the changed node or any of the changed node's parents. When it iterates up to the root node without finding a node that equals the scope's match, it then executes the `panic!`. 

In the above case, the changed node is the feature flag declaration which does have a `Class` parent node and certainly has a `File` / `(program)` parent node. I've tried attaching a debugger to Piranha but couldn't determine why `fn get_all_matches_for_query(...)` is not able to successfully complete (due to my lack of Rust knowledge). 

For context, the `piranha_arguments.toml` is:
```toml
language = ["java"]
substitutions = [
    ["flag_key_to_delete", "TEST_FF_KEY"]
]
```

**Comment by ketkarameya** [comment]
Hey! In this [PR](https://github.com/uber/piranha/pull/220) I added support for "File" scope for Java.  Are you using latest `master` ?

**Comment by ketkarameya** [comment]
Also you might want to take a look at the second rule. The `replace` field uses the tag `@lamba_function_body` but i do not see it initialized anywhere.

**Comment by Pencilvesterr** [comment]
This is running master from #230, so does include the changes for `File`. 

> Also you might want to take a look at the second rule.

This example was pulled from our more complicated real example. I've the `@lambda_function_body` and collected the files into [this](https://github.com/Pencilvesterr/scope_query_error_reproduction) repo for ease of reproduction & testing. Cheers :)

**Comment by ketkarameya** [comment]
Hey! i just tried your example on the latest master branch. It seems to work okay for me - it does'nt throw any exceptions. 

Can you try it again on current master? 

The steps I followed is : 
* Checkeout [this](https://github.com/Pencilvesterr/scope_query_error_reproduction) 
* Checkout Piranha 
* cd polyglot/piranha
* cargo build --release 
* cd target/release 
* ./polyglot_piranha -c <...>/scope_query_error_reproduction/test_cases -f  <...>/scope_query_error_reproduction/configurations

**Comment by Pencilvesterr** [comment]
Amazing, #233 fixes it :) Thanks for all your help!

**Comment by ketkarameya** [comment]
Closing this issue.
