### ISSUE TITLE
Support for JavaScript/TypeScript

### ISSUE THREAD

**Issue by techeverri** [uber/piranha#24]
Hey 👋

Do you have any plans to support JavaScript/TypeScript?

Thanks 👍

**Comment by mkruber** [comment]
Not currently planned. Contributions are welcome.

**Comment by techeverri** [comment]
Thanks for the quick reply @mkruber 👍 

Do you have a step-by-step guide on how to implement support for new languages?
_I mean something like the internal API docs with examples_

**Comment by mkruber** [comment]
Section 4.3 of this [report](https://github.com/uber/piranha/blob/master/report.pdf) discusses the overview of refactoring. In order to support Piranha for a new language, we will need to identify a good AST rewriter for that language and implement the Piranha logic on top of it. 

Unfortunately, nothing in the current implementation can be reused for cleaning up Javascript/Typescript code.

**Comment by techeverri** [comment]
Thanks for the link to the report 👍 
Section 4.3 doesn't have a lot of information though

**Comment by msridhar** [comment]
@techeverri for pure JavaScript you could use any parser (like [esprima](https://esprima.org)) to parse the code into a data structure, and then implement the logic for rewriting the code to get rid of flags.  Then you could use something like [escodegen](https://github.com/estools/escodegen) to write out the transformed code.  The general approach of Piranha will be the same, and you can look at the existing code for other languages to get an idea of how it should work.  But I doubt you will actually be able to re-use any of the existing Piranha code.  For TypeScript you might need different libraries for parsing and serialization.

**Comment by danew** [comment]
Facebook also have an open source tool which does both parts, the parsing to an AST and the code generation for the output. Could be worth looking at [jscodeshift](https://github.com/facebook/jscodeshift).

**Comment by mkr-plse** [comment]
Thanks for the pointer. We almost have an implementation for PiranhaJS ready to be open sourced and should be done in the next few days.
