### ISSUE TITLE
Provide Maven integration instruction

### ISSUE THREAD

**Issue by sivacoder** [uber/piranha#25]
See a well explained Gradle integration example. Would be good

1. To confirm if the tool would work with `maven`
2. If yes, a sample project would help.

BTW, tried on my maven project and struck with below error. Any help would be appreciated.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project myapp: Compilation failure
[ERROR] javac: invalid flag: -Xep:PatchChecks:Piranha
[ERROR] Usage: javac <options> <source files>
[ERROR] use --help for a list of possible options`

**Comment by msridhar** [comment]
You will need to get Error Prone working with your Maven build first.  See instructions under "Maven" here:

http://errorprone.info/docs/installation

After that, in principle adding the relevant flags for Piranha _should_ work.  However, I do not believe this has been tested by any of the maintainers.  If you get this working, a documentation contribution would be most welcome!

**Comment by sivacoder** [comment]
@msridhar - Thanks for quick response.

Yes, I did get the error-prone installation running fine in my project. The project builds with the jdk8 maven profile.

Trouble starts when I add in the Piranha related configuration. Looks like I'm out missing something core, that javac is crying about it.

My maven compiler configuration. **Bold** part is where compiler throws me out.
 
`    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <showWarnings>true</showWarnings>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.errorprone</groupId>
                            <artifactId>error_prone_core</artifactId>
                            <version>2.3.4</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-XDcompilePolicy=simple</arg>
                        <arg>-Xplugin:ErrorProne</arg>s
                        **<arg>-Xep:PatchChecks:Piranha</arg>
                        <arg>-XepOpt:Piranha:FlagName=my-test-flag</arg>**
                    </compilerArgs>
                </configuration>
            </plugin>`

`        <profile>
            <id>jdk8</id>
            <activation>
                <jdk>1.8</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                            <fork>true</fork>
                            <compilerArgs combine.children="append">
                                <arg>-J-Xbootclasspath/p:${settings.localRepository}/com/google/errorprone/javac/${javac.version}/javac-${javac.version}.jar</arg>
                            </compilerArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>`

I'm running as profile `mvn clean install -DskipTests -Pjdk8 -X`

Any pointers?

**Comment by msridhar** [comment]
I think you need to combine all the error prone arguments into a single Maven compiler `arg` when Error Prone is used as a plugin.  See the example here:

https://github.com/google/error-prone/issues/1242#issuecomment-554964390

**Comment by sivacoder** [comment]
@msridhar - Thanks for the details. The build went through fine with your suggestion.

But no traces of Piranha getting bootstrapped or executed to clean up the code. Is there a way to check if bootstrapping of Piranha in the application is fine? (meaning, configs are rightly put in)

BTW, I tried a spring boot template maven project and there too, do not see piranha getting invoked in `maven clean package -Pjdk8 -X`

Any pointers please?

**Comment by msridhar** [comment]
I’m not an expert on configuration of Piranha. Perhaps @mkruber or @lazaroclapp have an idea

**Comment by sivacoder** [comment]
@mkruber @lazaroclapp - Can you please help further?

**Comment by mkruber** [comment]
@sivacoder I don't think this is an issue with your config. It would have thrown an exception. 

In this case, it is looking for a memberselect on the function call (`DemoApplication.getIdvalue` instead of `getIdvalue`) which is not found. Can you change the call to the XP API from `getldvalue` to `DemoApplication.getldvalue` and see whether there is any difference? I tried it locally and found that the latter was being refactored and not the former.

**Comment by sivacoder** [comment]
@mkruber - We tried on the below sample test maven project with your above suggestion. 

But, still struck with bootstrapping of Piranha in the app. Any pointers?

Refer the pom integration here - https://github.com/sivacoder/java-maven-piranha-sample/blob/master/pom.xml#L68

Source code: https://github.com/sivacoder/java-maven-piranha-sample

**Comment by mkruber** [comment]
@sivacoder With the provided pom, I was unable to run any errorprone checker. 

So, used the `pom.xml` from this [link](https://github.com/google/error-prone/blob/v2.3.2/examples/maven/pom.xml) and added the following

```
          <showWarnings>true</showWarnings>
          <compilerArgs>
               <arg>-XDcompilePolicy=simple</arg>
               <arg>-Xplugin:ErrorProne -Xep:DeadException:WARN</arg>
            </compilerArgs>
          <annotationProcessorPaths>
            <path>
              <groupId>com.uber.piranha</groupId>
              <artifactId>piranha</artifactId>
              <version>0.0.3</version>
            </path>
            <path>
              <groupId>com.google.errorprone</groupId>
              <artifactId>error_prone_core</artifactId>
              <version>2.3.2</version>
            </path>
          </annotationProcessorPaths>
``` 
to ensure that errorprone is reporting some problem (added a dead exception to the provided source). 

Replacing EP arguments as follows 
`<arg>-Xplugin:ErrorProne -Xep:Piranha:WARN -Xep:PatchChecks:Piranha -Xep:PatchLocation:IN_PLACE -XepOpt:Piranha:FlagName=dummy_flag -XepOpt:Piranha:IsTreated=true -XepOpt:Piranha:Config=config/piranha.properties</arg>` results in an exception: 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project errorprone-example: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project errorprone-example: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1219)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:188)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
@msridhar @kageiit any suggestions here?

**Comment by mkruber** [comment]
@sivacoder I have updated instructions for Maven. See [here](https://github.com/uber/piranha/tree/master/java#maven-instructions)

There were a few typos in your `pom.xml`. `-Xep:PatchChecks:Piranha -Xep:PatchLocation:IN_PLACE` should have been `-XepPatchChecks:Piranha -Xep:PatchLocation:IN_PLACE`. 

It works for the example given for PiranhaJava. For the specific example given by you, since the flag name is a string literal ("dummy-flag") as opposed to some symbol, Piranha fails to refactor. If this is a blocker, let us know. It will be a simple fix.

**Comment by manishamishra2715** [comment]
Hi..using the above, I am able to run the maven based code succcessfully but if the flag is set to true, then the code inside it should be deleted automatically as per piranha rule.but the code still persists.can anyone please guide. Or if the expected output after deletion is coming on any folder?


if (Test.getldvalue("dummy-flag")) {
			System.out.println("success");
			
		}
		
		if(!Test.getldvalue("dummy-flag"))
		{ System.out.println("fail"); }

i mean to say the flag is set to true or false(-XepOpt:Piranha:IsTreated=true), then the following part of code should be deleted after the execution is over.But I am not getting the expected  output.

**Comment by manishamishra2715** [comment]
where can I get the refactored code after execution ? the source is not getting updated.please guide

**Comment by lazaroclapp** [comment]
> Hi..using the above, I am able to run the maven based code succcessfully but if the flag is set to true, then the code inside it should be deleted automatically as per piranha rule.but the code still persists.can anyone please guide. Or if the expected output after deletion is coming on any folder?
> 
> if (Test.getldvalue("dummy-flag")) {
> System.out.println("success");
> 
> ```
> 	}
> 	
> 	if(!Test.getldvalue("dummy-flag"))
> 	{ System.out.println("fail"); }
> ```
> 
> i mean to say the flag is set to true or false(-XepOpt:Piranha:IsTreated=true), then the following part of code should be deleted after the execution is over.But I am not getting the expected output.

Please note this explanation by @mkruber : 

> For the specific example given by you, since the flag name is a string literal ("dummy-flag") as opposed to some symbol, Piranha fails to refactor. If this is a blocker, let us know. It will be a simple fix to the check [here](https://github.com/uber/piranha/blob/master/java/piranha/src/main/java/com/uber/piranha/XPFlagCleaner.java#L294).

Piranha currently assumes that flags are fields of `enum` structures, not strings. It should be a fairly contained fix to add a check for string literals and we would be happy to review the PR (if you are at a loss on how to do it, let me know and I'll give it a crack when I get the chance, but it might be faster for you to do it :) )

**Comment by manishamishra2715** [comment]
Thank you for response.


[https://github.com/uber/piranha/blob/master/java/sample/src/main/java/com/uber/mylib/MyClass.java](url)
I checked the link u shared and also tried a sample example where flag is used as enum using maven(example as present in the above link). But how to get the expected output?? 
Can you please guide me the next steps ,like
1. do we have to run through main method or just running as Run As->maven test would work???
2. once the code is run,where can I check the output???

Please suggest if any changes needed for the above code.
And below is my pom.xml.

<modelVersion>4.0.0</modelVersion>
  <groupId>com.piranha.project</groupId>
  <artifactId>com.piranha.project</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
   





  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
        
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
          
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.7.0</version>
          
         <configuration>
          <source>8</source>
          <target>8</target>
           <showWarnings>true</showWarnings>
          <compilerArgs>
            <arg>-XDcompilePolicy=simple</arg>
            <arg>-Xplugin:ErrorProne -Xep:Piranha:WARN -XepPatchChecks:Piranha -XepPatchLocation:IN_PLACE -XepOpt:Piranha:FlagName=SAMPLE_STALE_FLAG -XepOpt:Piranha:IsTreated=true -XepOpt:Piranha:Config=config/piranha.properties</arg>
          </compilerArgs>
          <annotationProcessorPaths>
            <path>
              <groupId>com.uber.piranha</groupId>
              <artifactId>piranha</artifactId>
              <version>0.0.3</version>
            </path>
            <path>
              <groupId>com.google.errorprone</groupId>
              <artifactId>error_prone_core</artifactId>
              <version>2.3.2</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.20.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>

**Comment by sivacoder** [comment]
First of all, thank TEAM (@mkruber @lazaroclapp @msridhar ) for the timely support on this one. Happy to say we are able to get it integrated with our maven application and it works as per the spec specified.

But, we found a few extension cases we need where the current removal code is not supporting:

1. Ability to use string-literal
`getldvalue("dummy-flag")`

2. Ability to use constants
`
private static final String STALE_FLAG_NAME = "dummy-flag";
getldvalue(STALE_FLAG_NAME)
`

3. Control methods with more than 1 argument
`
getldvalue(STALE_FLAG_NAME, paramter1, parameter 2)
`

4. Removing dangling boolean variable
`
boolean isFlagEnabled = getldvalue(STALE_FLAG_NAME);
if(isFlagEnabled) {
    System.out.println("success");
}

Piranha converts this to:

boolean isFlagEnabled = true;
if(isFlagEnabled) {
    System.out.println("success");
}

`

**Comment by mkruber** [comment]
> First of all, thank TEAM (@mkruber @lazaroclapp @msridhar ) for the timely support on this one. Happy to say we are able to get it integrated with our maven application and it works as per the spec specified.

You are welcome. Filed a separate issue to discuss the extensions.

**Comment by mkruber** [comment]
> Thank you for response.
> 
> [https://github.com/uber/piranha/blob/master/java/sample/src/main/java/com/uber/mylib/MyClass.java](url)
> I checked the link u shared and also tried a sample example where flag is used as enum using maven(example as present in the above link). But how to get the expected output??
> Can you please guide me the next steps ,like
> 
> 1. do we have to run through main method or just running as Run As->maven test would work???
> 2. once the code is run,where can I check the output???

`mvn clean compile` from command line should create the changes in the source code (in place).
