### ISSUE TITLE
deep cleanup is not working with demo for kt and java

### ISSUE THREAD

**Issue by nagraj-ec** [uber/piranha#250]
as per the instruction, running  `demo/stale_feature_flag_cleanup_demos.py` is expected to do deep clean ups.
Version : polyglot-piranha-0.1.2 , Apple M1 Max, Version 12.5.1

Before the stale_feature_flag_cleanup_demos

```
class SampleKotlin {

     fun print_status_enabled() {
        if (experimentation.isToggleEnabled(SAMPLE_STALE_FLAG)) {
            println("SAMPLE_STALE_FLAG is enabled")
        } else {
            println("SAMPLE_STALE_FLAG is disabled")
        }
    }

    fun print_status_disabled() {
        if (experimentation.isToggleDisabled(SAMPLE_STALE_FLAG)) {
            println("SAMPLE_STALE_FLAG is disabled")
        } else {
            println("SAMPLE_STALE_FLAG is enabled")
        }
    }
}
```

After the stale_feature_flag_cleanup_demos

```
class SampleKotlin {

     fun print_status_enabled() {
        if (true) {
            println("SAMPLE_STALE_FLAG is enabled")
        } else {
            println("SAMPLE_STALE_FLAG is disabled")
        }
    }

    fun print_status_disabled() {
        if (false) {
            println("SAMPLE_STALE_FLAG is disabled")
        } else {
            println("SAMPLE_STALE_FLAG is enabled")
        }
    }
} 
```

isn't it expected to have deep clean ups with piranha-polyglot ?

**Comment by dvmarcilio** [comment]
Thanks for reporting this @nagraj-ec. I also got the same output when installing polyglot-piranha-0.1.2 through `pip install polyglot-piranha`, but not from source. It looks like a new version needs to be published to PyPI.

Could you report back after running the demo again by installing from source (`pip install .`)?

**Comment by ketkarameya** [comment]
@nagraj-ec thanks for reporting this. Yes I observed this issue on ubuntu too. The problem was that the built-in cleanup rules are not being packaged in the wheel.  I have fixed the problem in #247 . I have not made a release yet, will do it this week.

**Comment by nagraj-ec** [comment]
thanks @dvmarcilio @ketkarameya for the response, I tried installing from the source `(pip install .)`, could able to successfully install polyglot_piranha-0.1.2. But running the demo scripts encountering below issues

```
from polyglot_piranha import run_piranha_cli
  File "/Users/nagaraj/oscode/piranha/polyglot/piranha/.env/lib/python3.9/site-packages/polyglot_piranha/__init__.py", line 1, in <module>
    from .polyglot_piranha import *
ImportError: dlopen(/Users/nagaraj/oscode/piranha/polyglot/piranha/.env/lib/python3.9/site-packages/polyglot_piranha/polyglot_piranha.cpython-39-darwin.so, 0x0002): tried: '/Users/nagaraj/oscode/piranha/polyglot/piranha/.env/lib/python3.9/site-packages/polyglot_piranha/polyglot_piranha.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))) 
```

I am on Apple M1 Max, OS Version 12.6

**Comment by ketkarameya** [comment]
Can you please try : 
```
cd polyglot/piranha
python3 -m venv .env
source .env/bin/activate
pip install maturin
maturin develop
```
You might have to install [Rust](https://rustup.rs/) 

Try to run the demos after this.

**Comment by ketkarameya** [comment]
do you have a virtual environment activated before you tried `pip install .`? If not, can u please try :   
```
cd polyglot/piranha
python3 -m venv .env
source .env/bin/activate
pip install .
```

**Comment by nagraj-ec** [comment]
Have virtual environment activated before running pip install ., i guess its MAC M1 causing the issue.
`rustup show` causes
Default host: aarch64-apple-darwin
