### ISSUE TITLE
Better Python `PiranhaOutputSummary`

### ISSUE THREAD

**Issue by dvmarcilio** [uber/piranha#272]
Currently, it's not easy to manipulate a `PiranhaOutputSummary` returned by the Python API.
As seen below, printing and traversing the summary can be non-intuitive. 
Some ideas to ease the burden:

- pretty print the summary and nested classes
- expose the summary classes as typed python classes. ideally, this would lead to IDE autocompletion

```python
summary = run_piranha_cli(codebase_path, configs_path, True)
print(summary) # <builtins.Range object at 0x7fc0e9ed5228>

for s in summary:
  for rewrite in s.rewrites:
    print(rewrite) # <builtins.Edit object at 0x7f108e84d618>
    print(rewrite.p_match) # <builtins.Match object at 0x7f43f2233af8>
    print(rewrite.p_match.range) # <builtins.Range object at 0x7f108e76f270>
```

**Comment by ketkarameya** [comment]
Address using https://pyo3.rs/main/class/object#basic-object-customization
