### ISSUE TITLE
Extensions for PiranhaJava

### ISSUE THREAD

**Issue by mkr-plse** [uber/piranha#28]
Following up on issue [25](https://github.com/uber/piranha/issues/25), the following extensions were requested by @sivacoder:

> But, we found a few extension cases we need where the current removal code is not supporting:
> 
> 1. Ability to use string-literal
>    `getldvalue("dummy-flag")`
> 2. Ability to use constants
>    `private static final String STALE_FLAG_NAME = "dummy-flag"; getldvalue(STALE_FLAG_NAME)`
> 3. Control methods with more than 1 argument
>    `getldvalue(STALE_FLAG_NAME, paramter1, parameter 2)`
> 4. Removing dangling boolean variable
>    ` boolean isFlagEnabled = getldvalue(STALE_FLAG_NAME);`
>    `if (isFlagEnabled) {`
>    `      System.out.println("success");`
>    `}`
> 
> Piranha converts to
> `boolean isFlagEnabled = true;`
> `if(isFlagEnabled) {`
> ` System.out.println("success");`
> `}`
> 
> @lazaroclapp - Happy to contribute if we can have a quick sync on how to go about it. Looking forward

Filing this issue to continue the discussions here.

**Comment by lazaroclapp** [comment]
@sivacoder @mkruber 
I'd say the first two are fairly closely related and are easy to address. It involves extending the code of `getXPAPI` [here](https://github.com/uber/piranha/blob/master/java/piranha/src/main/java/com/uber/piranha/XPFlagCleaner.java#L294). 

Currently, it takes a look at `arg` and immediately casts it to a symbol, which it then matches against a symbol/enum name. We need to add two additional tests:

a) If `arg` is a string literal (e.g. if `com.sun.source.tree.LiteralTree` is the type, I believe) then match it's value directly against `xpFlagName`
b) If `argSym` (the symbol) is a field, then we need to check first if it's a constant (`static final`), and if so compare its value against `xpFlagName` (not sure if there is an easy way to get the declaration given a symbol or if you'd need to build a map during `matchVariable`, `matchClass` or some other matcher)

Fixing (3) will require adding info to the config format, namely changing from "list of methods" to "list of method, arg# pair". Right now I am not sure how involved that will be.

Finally, (4) seems like a bug, let's get the others done, produce a test case and then we can start looking into it :) 

I'd say (1)/(a) above is good first PR.

**Comment by msridhar** [comment]
For b), I think there should be some way to get the `Tree` based on the `Symbol`.  NullAway does it like this:

https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/NullAway.java#L628

Then from the right-hand side of the declaration, you could use code like this to get the constant value:

https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/util/ASTHelpers.java#L1011

At least I _think_ that should work.

**Comment by manishamishra2715** [comment]
Hi...first of all thank you for all suggestions you gave fo the issue I raised last time(#25).
I followed all the steps required for piranha integration , but I am getting some unexpected output.
For the simple code link which I shared before, I did mvn clean compile  to get output.
But it is removing the flag name inside code.

enum TestExperimentName {
		SAMPLE_STALE_FLAG;
	
	}

for the above part of code, it is giving output as:

enum TestExperimentName {
		;
	
	}

It is not removing the code written inside any method.

sample  code link:  
https://github.com/uber/piranha/blob/master/java/sample/src/main/java/com/uber/mylib/MyClass.java

The source code is getting updated but with wrong output.
Please help me to resolve this.

**Comment by sivacoder** [comment]
@manishamishra2715 - This ticket is to discuss new extensions support. Is it fair for you to create a separate ticket and discuss this issue rather than polluting this one? It's easier to report, trace, fix, and for other who will face the same issue to search and find.

Hopefully, it makes sense.

**Comment by sivacoder** [comment]
@lazaroclapp  @mkruber @msridhar - For #1 and #2, we have raised this PR - https://github.com/uber/piranha/pull/30

Please review

**Comment by sivacoder** [comment]
@mkruber @lazaroclapp @msridhar - Can you help with the next steps for #3 and #4 extensions?

**Comment by mkruber** [comment]
I assume you are referring to 3 and 4 above. The links pointed in the comment refer to different issues. 

For issue 3, I propose deleting the checks for argument count [here](https://github.com/uber/piranha/blob/master/java/piranha/src/main/java/com/uber/piranha/XPFlagCleaner.java#L291). This still assumes that the first argument is the flag name. If you want to extend this further where flag name can be at any index, you will have to update the `piranha.properties` file and update the checks for flag name comparison to also include the index mentioned in the properties file. 

For issue 4, there are many ways of handling it. It will require two passes. In the first pass, remember all assignments where the RHS contains the flag API expression and the result of the RHS. In the second pass, delete these assignment expressions and where ever the fully qualified name of the LHS occurs (for local variables, maybe you can use the Class name + methodname + variable name) to determine the FQN) and evaluate expressions. This change will be involved -- so propose that this be handled in a separate PR. You can take a look at the deepclean [pass](https://github.com/uber/piranha/blob/master/swift/src/CleanupStaleFlags/StaleFlagCleaner.swift#L509) of PiranhaSwift for the general strategy.

**Comment by mkr-plse** [comment]
1,2 and 3 are already addressed. 4 is being tracked elsewhere (e.g., #58)
