### ISSUE TITLE
General: Figure out a flow for deleting full files for external adopters.

### ISSUE THREAD

**Issue by lazaroclapp** [uber/piranha#4]
See #2 and [this comment thread](https://github.com/uber/piranha/pull/1/files/f916e2e7b1e22e8488fde0be57f5c82545e9013f#r342228570). 

What is the best way for external users to integrate Piranha? EP_PATCH_CHECK followed by file clean up script like we do? Something else?

**Comment by ketkarameya** [comment]
@lazaroclapp I am closing this issue for now.  I guess it is resolved, since we have successfully released Piranha with Error prone.
