### ISSUE TITLE
PiranhaJava // Use Immutable structures (List/Map) for config data

### ISSUE THREAD

**Issue by pranavsb** [uber/piranha#41]
In XPFlagCleaner, mutable structures are currently used. 

----------------------------------------------------------------
 I'd prefer `ImmutableMap` and `ImmutableList` here and builders. But since the original code was also using mutable collections, I am absolutely fine leaving that for a follow up issue you two can assign to me 😅

_Originally posted by @lazaroclapp in https://github.com/uber/piranha/pull/39_

**Comment by mkr-plse** [comment]
Resolved in #55
