### ISSUE TITLE
PiranhaJava // Potential string compare bug in matchIf

### ISSUE THREAD

**Issue by pranavsb** [uber/piranha#42]
In `XPFlagCleaner`, the `public Description matchIf(IfTree ifTree, VisitorState visitorState)` method uses the equality operator `==` for String comparison instead of `.equals`

`if (update) {
      if (replacementPrefix != EMPTY) {
        replacementString = replacementPrefix + replacementString;
      }`

https://github.com/uber/piranha/blob/dd050f86315ab3e719fa5d22d7f0039ad844b039/java/piranha/src/main/java/com/uber/piranha/XPFlagCleaner.java#L853

**Comment by mkr-plse** [comment]
Fixed in #45
