### ISSUE TITLE
PiranhaJava // minor - avoid simplifying when xpFlagName is empty string ("")

### ISSUE THREAD

**Issue by pranavsb** [uber/piranha#44]
Running Piranha with `-XepOpt:Piranha:FlagName=""` results in the deletion of all static imports.

Two places in `XPFlagCleaner` can cause this, because the code is `.endsWith(xpFlagName)` when comparing with expressions. Since `xpFlagName` is `""`, that always evaluates to true.

The specific places are: 
https://github.com/uber/piranha/blob/dd050f86315ab3e719fa5d22d7f0039ad844b039/java/piranha/src/main/java/com/uber/piranha/XPFlagCleaner.java#L534

and

https://github.com/uber/piranha/blob/dd050f86315ab3e719fa5d22d7f0039ad844b039/java/piranha/src/main/java/com/uber/piranha/XPFlagCleaner.java#L726

The second case seems to be rarer.

The can be fixed with another check `!xpFlagName.equals(EMPTY)`

**Comment by swayamraina** [comment]
The second case mentioned by @pranavsb will actually impact users who write test cases using configuration (or profile) based test cases powered using annotations
