### ISSUE TITLE
PiranhaJava // Decouple configMethodProperties from its JSON representation

### ISSUE THREAD

**Issue by pranavsb** [uber/piranha#48]
configMethodProperties in XPFlagCleaner is currently a `Map<String, List<Map<String, Object>>>`.
The `Map<String, Object>` should be replaced with a custom class, like `PiranhaMethodRecord` so it is decoupled from the config file and Piranha can be easily extended to other config specification formats.

For context and details see these comments:
https://github.com/uber/piranha/pull/39#discussion_r436899257
https://github.com/uber/piranha/pull/39#discussion_r430695822

**Comment by mkr-plse** [comment]
This is resolved in #55
