### ISSUE TITLE
PiranhaSwift: Use properties.json file to specify configuration

### ISSUE THREAD

**Issue by mkr-plse** [uber/piranha#52]
Currently PiranhaSwift APIs are specified using a properties file as shown [here](https://github.com/uber/piranha/blob/master/swift/piranha.properties).  It will be helpful to migrate this to use a json file so that more properties can be specified easily. For instance, it could be an array of `methodProperties` where the `methodName`, `flagType`, `returnType` and `argumentIndex` of the flag are specified. Example:

{ "methodProperties": [ { "methodName": "isToggleEnabled", "flagType": "treated", "returnType": "boolean", "argumentIndex": 0 }, ... ], }

This properties file will be parsed and the listed APIs will be used for refactoring.

**Comment by chiragramani** [comment]
I can take this up 👍🏼

**Comment by mkr-plse** [comment]
> I can take this up 👍🏼

thanks. assigned it to you.

**Comment by mkr-plse** [comment]
Fixed in #118
