### ISSUE TITLE
[question] : how to run sample app in intelliJ locally

### ISSUE THREAD

**Issue by swayamraina** [uber/piranha#53]
how to run sample app in intelliJ locally?

This will help in understanding and contributing the code. Post this we can add setup and run guidelines to the README.

**Comment by mkr-plse** [comment]
Once you have the ErrorProne plugin (as described [here](http://errorprone.info/docs/installation)), you can pass the appropriate options for Piranha and it should work.

**Comment by mkr-plse** [comment]
@swayamraina Did this work for you? If so, feel free to open a PR to update the doc. 
Also, you can ask questions in the gitter channel.

**Comment by swayamraina** [comment]
Sure, will raise a small PR to update the readme.

I was able to run the project against sanple app but not able to run in debug mode.

**Comment by tracelou73** [comment]
> pr

**Comment by swayamraina** [comment]
PR: https://github.com/uber/piranha/pull/59
Have added block regarding 'how to run sample app', do review and comment if you feel something more needs to be added.

**Comment by mkr-plse** [comment]
Since the ErrorProne installation link is available from README and nothing else needs to be added to the docs, closing this issue.
