### ISSUE TITLE
[PiranhaAgent] support for TS

### ISSUE THREAD

**Issue by alex-from-intuita** [uber/piranha#562]
@grzpab added TS for piranha. what would it take to add support in PiranhaAgent?
@ketkarameya 
![Screenshot 2023-07-27 at 12 08 53 AM](https://github.com/uber/piranha/assets/78109534/6a526cd5-b284-4e4f-8d8c-69c16331d5cb)

**Comment by alex-from-intuita** [comment]
@ketkarameya / @danieltrt any ideas? thanks

**Comment by danieltrt** [comment]
You would need to add the parser here 

https://github.com/uber/piranha/blob/3a19a5c64e316dfc08bce1b52b1ab8b971365b7d/experimental/piranha_playground/rule_inference/template_parser.py#L24

https://github.com/uber/piranha/blob/3a19a5c64e316dfc08bce1b52b1ab8b971365b7d/experimental/piranha_playground/data_validation.py#L18

https://github.com/uber/piranha/blob/3a19a5c64e316dfc08bce1b52b1ab8b971365b7d/experimental/piranha_playground/templates/index.html#L30

I’m not sure if TS is part of the tree sitter language Python package though. If not you’d need to compile and the language manually

**Comment by alex-from-intuita** [comment]
thanks daniel. i consider this as closed for now. cc @grzpab
