### ISSUE TITLE
remove experiment name enum class from tests

### ISSUE THREAD

**Issue by swayamraina** [uber/piranha#66]
I see a pending task of removing `enum TestExperimentName` from tests
This is also marked as todo in code as `// Ideally we would remove this too, fix later`
This acts as a boilerplate when adding new test cases and should be removed.

This can be fixed by simply creating a class similar to `XPTest` under test resources and creating handler function like `assertFeatureFlags (String flags...)`
This new function will create the output enum file with provided input flags.

**Comment by mkr-plse** [comment]
This is not a problem with tests alone. If the set of flags are removed and the enum becomes empty, Piranha should delete the entire file.

**Comment by swayamraina** [comment]
i guess then this should be marked as a duplicate or dependent on https://github.com/uber/piranha/issues/58

**Comment by ketkarameya** [comment]
@mkr-plse @swayamraina I am closing this issue. With polyglot piranha we can now delete empty enums, and files with empty enums/classes. Please feel free to reopen, if you have any questions.
