### ISSUE TITLE
How Java or Spring Boot projects should integrate with Uber Piranha

### ISSUE THREAD

**Issue by rajeshchinnam** [uber/piranha#692]
I tried adding this dependency but this is not getting resolved

`<dependency>
    <groupId>com.uber.piranha</groupId>
    <artifactId>piranha</artifactId>
    <version>0.1.8</version>
</dependency>`

I cloned https://github.com/uber/piranha but i didn't find pom.xml

as per documentation I see it supports java but how to integrate with spring boot project

**Comment by danieltrt** [comment]
Hi @rajeshchinnam. Piranha does indeed support Java (as in it can transform / cleanup Java code). However, the tool itself is written in rust and it also has python bindings (which you can get prom PyPI using pip). See the example in the README to get started with it. Piranha itself is not a java package.

**Comment by rajeshchinnam** [comment]
Thanks @danieltrt  so if I have to integrate Piranha with spring boot application to clean-up feature toggles 
can you please suggest what are the steps I need to follow , if any documentation is available please let me know
That would be of great help.

I am trying adding maven jar and plugins but unsuccessful to run 

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.3</version>
    <relativePath /> 
  </parent>
  <groupId>com.piranha</groupId>
  <artifactId>demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>piranha</name>
  <description>Demo project for Spring Boot piranha</description>
  <url />
  <licenses>
    <license />
  </licenses>
  <developers>
    <developer />
  </developers>
  <scm>
    <connection />
    <developerConnection />
    <tag />
    <url />
  </scm>
  <properties>
    <java.version>21</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>com.uber.piranha</groupId>
      <artifactId>piranha</artifactId>
      <version>0.1.8</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.uber.piranha</groupId>
        <artifactId>piranha-maven-plugin</artifactId>
        <version>0.1.8</version>
        <executions>
          <execution>
            <phase>process-sources</phase>
            <goals>
              <goal>remove</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>`
