### ISSUE TITLE
Request to publish package to crates.io

### ISSUE THREAD

**Issue by shubhamBETA** [uber/piranha#700]
Issue Description:

- We are interested in using this Rust library in our internal systems. To facilitate the possible integration, we kindly request that the active maintainer of the package consider publishing this package to [crates.io](crates.io), the official Rust package registry.

- Publishing to crates.io is the only way we can use this library as internally all third party imports are approved to be taken from crates.io.

- I checked with the author of the library (Murali Krishna Ramanathan), he asked me to open this Github ticket so that active maintainer can help us out here.

Thank you for considering this request and for your valuable contribution to the Rust ecosystem.

**Comment by ketkarameya** [comment]
Hey @shubhamBETA thanks a lot for reaching out. 
While this is a rust codebase (or a rust based tool), we do not expose it as a rust library. We rather publish it as a python package on pip. 
https://pypi.org/project/polyglot-piranha/

Is there a specific reason you want to use it as a rust library? You could potentially contribute to cleanup its current rust-api and expose it as a rust library too. But publishing at crates.io is something that Uber OSS will have to do. We will have to check that with deigo, though . At Uber, the tool is used as a Python library.

**Comment by shubhamBETA** [comment]
Thanks Ameya for responding.

- I see, I wasn't aware this is published as python package on pip already.
- I thought it is primarily a Rust library, since majority code written in Rust (35%).
- Now I can give it a shot to import internally via pip route, since you also mentioned that at Uber the tool is used as Python library 

On a side note, read you and your team's blogs for the stuff being built at Gitar.co, Pretty cool stuff man!

I'll mark this as closed. Thanks
Shubham

**Comment by ketkarameya** [comment]
There are a bunch of examples here - https://github.com/uber/piranha/tree/master/demo
You can use these to get yourself started

**Comment by ketkarameya** [comment]
ITs a 100% rust library, we use https://pyo3.rs/v0.22.3/ to create a python api

**Comment by shubhamBETA** [comment]
okay, makes sense. I will take a look.
Thanks!
