### ISSUE TITLE
Polyglot piranha - usage of "@" character in the replacement query

### ISSUE THREAD

**Issue by aleksandr-zakshevskii-n26** [uber/piranha#712]
Hello people,

I wonder if its possible to use a "@" character in the replacement query?

I use the following code:

```
replace = "\\@SuppresWarnings(\"UnusedPrivateProperty\") @some_var"

```

Which produces syntactically incorrect code:
```\@SuppresWarnings("UnusedPrivateProperty")```
If I don't escape the @ character - Piranha hangs.

I would be appreciated for your help.
Thanks.

**Comment by danieltrt** [comment]
Do you have the entire rule? I suspect you're just not getting the infinite loop because of the syntax error

**Comment by aleksandr-zakshevskii-n26** [comment]
Hey just small update:
in the folder `demo/find_replace_custom_cleanup` there is an example which I guess related to my issue:
there is the rule `add_import_statement` in the folder `java/configurations`
which does exactly what I want:
```
name = "add_import_statement"
query = "(package_declaration (_)@package_name) @package_declaration"
replace_node = "package_declaration"
replace = "@package_declaration\nimport java.util.Collections;\n"
```

it appends `java.util.Collections` import after a package declaration. I adjusted this example for Kotlin:
```
[[rules]]
name = "add_import_statement"
query = "(package_header (_)@package_name) @package_declaration"
replace_node = "package_declaration"
replace = "@package_declaration\nimport java.util.Collections;\n"
groups = ["Cleanup Rule"]
```

And it appears to have the same problem - it goes to the infinite loop when running this example. This is the full example:

```python
from polyglot_piranha import execute_piranha, PiranhaArguments, Rule, RuleGraph, OutgoingEdges

# Toy code snippet
code = """
package com.test

class Sample(private val test: Int) {
}
"""
r1 = Rule(
    name="add_import_statement",
    query="(package_header (_)@package_name) @package_declaration",
    replace_node="package_declaration",
    replace="@package_declaration\nimport java.util.Collections;\n",
)

# Create Piranha arguments
piranha_arguments = PiranhaArguments(
    code_snippet=code,
    language="kt",
    rule_graph=RuleGraph(rules=[r1], edges=[],)
)

piranha_summary = execute_piranha(piranha_arguments)
print(piranha_summary[0].content)
```

**Comment by danieltrt** [comment]
I think the solution here is to add an enclosing node filter, or you can use tree sitter syntax for node absence to make sure the rule isn’t triggered twice



Negated Fields

You can also constrain a pattern so that it only matches nodes that lack a certain field. To do this, add a field name prefixed by a ! within the parent pattern. For example, this pattern would match a class declaration with no type parameters:

```

(class_declaration
  name: (identifier) @class_name
  !type_parameters)

```

**Comment by danieltrt** [comment]
Or you can otherwise make sure the modifiers do not include a surpress warning with a regex predicate

**Comment by aleksandr-zakshevskii-n26** [comment]
Nice idea! I will try to add a regex predicate to not match fields with the @SuppressWarning annotation, thanks!
