### ISSUE TITLE
PiranhaJava: Sample application does not build on Oracle JDK 9.0+

### ISSUE THREAD

**Issue by atrakh** [uber/piranha#72]
Unsure if this is a trivial fix or not, but I was unable to get the sample application included in this repository to work with Java version 9.0 or higher. Downgrading to Java 8 resolved the issue for me

```bash
$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

$ ./gradlew test
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :piranha:test FAILED
Error: Could not create the Java Virtual Machine.
-Xbootclasspath/p is no longer a supported option.
```

**Comment by ketkarameya** [comment]
@atrakh please try polyglot piranha. It should work irrespective of your Java language version. I am closing this issue for now. Please feel free to reopen in case you are facing any difficulties using it.
