### ISSUE TITLE
Config file not found exception disables PiranhaJava refactoring silently

### ISSUE THREAD

**Issue by vihanparmar** [uber/piranha#76]
I am trying the sample java gradle project and after running clean build piranha only removes the SAMPLE_STALE_FLAG enum but not the code checks. This is the output - 

```
public class MyClass {

  enum TestExperimentName {
    //REMOVED FROM HERE BUT NOT BELOW
  }

  private XPTest expt;

  public void foo() {
    if (expt.flagEnabled(TestExperimentName.SAMPLE_STALE_FLAG)) {
      System.out.println("Hello World");
    }

  }

  public void bar() {
    if (expt.flagDisabled(TestExperimentName.SAMPLE_STALE_FLAG)) {
      System.out.println("Hi World");
    }
  }

  static class XPTest {
    public boolean flagEnabled(TestExperimentName x) {
      return true;
    }

    public boolean enableFlag(TestExperimentName x) {
      return true;
    }

    public boolean disableFlag(TestExperimentName x) {
      return true;
    }

    public boolean flagDisabled(TestExperimentName x) {
      return true;
    }
  }
}
```

Here is my gradle file - https://github.com/vihanparmar/testRepo/blob/master/test/build.gradle

Please let me know what i am doing wrong or if this is an issue.

**Comment by mkr-plse** [comment]
The exception [here](https://github.com/uber/piranha/blob/master/java/piranha/src/main/java/com/uber/piranha/XPFlagCleaner.java#L221) is thrown, thereby, disabling any refactoring. Fix to this will involve handling the exception and also showing a clear warning that the refactoring will not happen correctly because of this exception.

**Comment by vihanparmar** [comment]
Why is it throwing that exception? I have added a config here https://github.com/vihanparmar/testRepo/blob/058805be85d1eadf0e49d8ec3e848516f96f1d62/test/build.gradle#L41

**Comment by mkr-plse** [comment]
Some issue with handling relative paths in the implementation. So, the interim workaround until this issue is resolved is to provide the absolute path for `-XepOpt:Piranha:Config`.

**Comment by vihanparmar** [comment]
I tried
`    options.errorprone.errorproneArgs.add("-XepOpt:Piranha:Config=Users/vparmar/Documents/GitHub/testRepo/test/config/properties.json")
`
still no luck

**Comment by vihanparmar** [comment]
Never mind, i updated piranha to 0.1.0 and it worked, thanks for the help.
