### ISSUE TITLE
Would this be possible in a framework like Ruby or Rails

### ISSUE THREAD

**Issue by Bennet-Sunder** [uber/piranha#80]
Considering that ruby is not statically typed and has meta-programming where it's hard to find the references of a particular flag. Just curious about the possibilities.

**Comment by mkr-plse** [comment]
It is possible to implement a variant of Piranha for ruby using [Parser](https://github.com/whitequark/parser). As for your question on finding references to a particular flag, it depends on the coding style, the availability of tools to perform alias analysis, etc. If you can share some examples on expected refactorings, I can clarify further.

**Comment by ketkarameya** [comment]
@Bennet-Sunder This can now be done by adding support for Ruby in polyglot-piranha .

**Comment by Bennet-Sunder** [comment]
@mkr-plse @ketkarameya just as a heads up I have submitted a draft PR for adding support for ruby. Will clean it up and mark it ready by next week.

**Comment by juamanti** [comment]
Hello, @Bennet-Sunder what's the progress on adding support for ruby?

**Comment by juamanti** [comment]
Let us know since our org would like to integrate with Piranha, pending with that integration

**Comment by Bennet-Sunder** [comment]
@juamanti it should be merged shortly, you can follow the PR for updates on when it'll be merged. In the meanwhile you can evaluate it using my fork.

**Comment by juamanti** [comment]
Will do!

**Comment by Bennet-Sunder** [comment]
@juamanti support for ruby is now merged (https://github.com/uber/piranha/pull/649) and it should be available in the next release.

**Comment by juamanti** [comment]
Thank you so much!! cc: @Charan Mahesan ***@***.***>

Best, Juan
