### ISSUE TITLE
[PiranhaJS] Remove declaration of the identifier

### ISSUE THREAD

**Issue by mkr-plse** [uber/piranha#92]
Is it planned for Piranha to support refactoring/removing the declaration of the identifier argument?
e.g. removing all of the code in this block, instead of just the conditional block:
```javascript
const featureFlag = "feature-flag"
if (isFlagTreated(featureFlag)) {
 // do stuff
}
```

If we had that functionality, we could likely make the assumption that the configured API argument index always refers to a string literal and expect the flag name to be a string literal node. Being able to search across multiple files/imports would likely be required for some of the more complex usages of feature flags

_Originally posted by @atrakh in https://github.com/uber/piranha/pull/91#issuecomment-673189583_

**Comment by anag004** [comment]
Not sure if this is relevant, but we might need to make PiranhaJS aware of variable scope here. Without this, the following code 
```javascript
{ var featureFlag = "feature1-flag"; } // scope 1

// ...

{ var featureFlag = "feature2-flag"; } // scope 2
```

will be refactored incorrectly when cleaning up one of the flags. For example, when cleaning up `"feature1-flag"`,  `featureFlag` will be replaced by `"feature1-flag"` everywhere.

**Comment by msridhar** [comment]
The escope library can be helpful for variable scopes:

https://github.com/estools/escope

**Comment by atrakh** [comment]
> Not sure if this is relevant, but we might need to make PiranhaJS aware of variable scope here.

Good point... this is some of the magic I hand-waved away 😄

**Comment by ketkarameya** [comment]
@atrakh we can now perform this kind of cleanup in [polyglot piranha](https://github.com/uber/piranha/tree/master/polyglot). 
However, on-boarding JS of Polyglot Piranha is pending. 
I am closing this issue for now, since polyglot piranha allows developers to support for such cleanups.  
Feel free to reopen this issue if you have further questions.
