### ISSUE TITLE
Running the Piranha Pipeline to automatically detect unused flags

### ISSUE THREAD

**Issue by aakriti-kedia** [uber/piranha#96]
[PiranhaJava](https://github.com/uber/piranha/tree/master/java) directs through the steps for running piranha with flagName specified in the pom.xml but the Piranha paper states that there is a Piranha pipeline that runs automatically in some scheduled intervals to detect state flags. Is there a sample project to get started with the Piranha pipeline ? Also is it possible to trigger the pipeline manually ?

**Comment by mkr-plse** [comment]
The Piranha pipelines discussed in the paper is not open sourced but we can consider adding a sample project to demonstrate this. Until then, the high level idea is: 

1. Obtain the list of stale flags and flag owners from the flag management system (e.g., launchdarkly, unleash, ...)
2. Invoke Piranha with the obtained stale flag and treatment behavior to generate the patch
3. Use the owner info from step 1 to create a task for the owner (Jira, Phab, GitIssue, ....)
4. Post the patch for code review (PR, Phab diff, ...)

**Comment by sivacoder** [comment]
@mkr-plse - Would be helpful to share a sample project demonstrating the pipeline structure and so on.

More specifically on:

1. Can multiple feature flags be fed to Piranha in one run? Saw your [engg blog on this](https://eng.uber.com/piranha/) and seems like a scheduler is fed with list of flags. Can you share more on this?
2. Can the `flagType` parameter in properties.json be configured per flag?

**Comment by mkr-plse** [comment]
> More specifically on:
> 
> 1. Can multiple feature flags be fed to Piranha in one run? Saw your [engg blog on this](https://eng.uber.com/piranha/) and seems like a scheduler is fed with list of flags. Can you share more on this?

Piranha will only refactor one flag at a time. However, if the goal is to have multiple flags cleaned up as part of one PR, then a wrapper script can invoke Piranha for each flag and accumulate the patch. Once all the invocations are performed, a PR based on the accumulated patch can be created. This has not been tested effectively and may not work _always_. If cleanup of the first flag introduces changes that can cause a compiler error, then the second flag will not be refactored. Therefore, recommend cleaning up one flag at a time, posting a PR, ... 

> 2. Can the `flagType` parameter in properties.json be configured per flag?

The properties in properties.json are repo specific. For example,
```
      "methodName": "isToggleEnabled",
      "flagType": "treated",
      "returnType": "boolean",
      "argumentIndex": 0
```
suggests that any method named `isToggleEnabled` will be considered a `treated` method returning a boolean value and the flagname is used at index 0. 

So, if the code for refactoring is as follows: 
```
if(isToggleEnabled(SOME_STALE_FLAG)) {
    print("treated");
} else {
    print("control");
}
```

and Piranha is invoked with 
```
  options.errorprone.errorproneArgs << -XepOpt:Piranha:FlagName=SOME_STALE_FLAG"
  options.errorprone.errorproneArgs << "-XepOpt:Piranha:IsTreated=true"
  options.errorprone.errorproneArgs << "-XepOpt:Piranha:Config=config/properties.json"
``` 

then the code refactors to 

```
print("treated");
```

But, if Piranha is invoked with 

```
  options.errorprone.errorproneArgs << -XepOpt:Piranha:FlagName=SOME_STALE_FLAG"
  options.errorprone.errorproneArgs << "-XepOpt:Piranha:IsTreated=false"
  options.errorprone.errorproneArgs << "-XepOpt:Piranha:Config=config/properties.json"
}
``` 

then the code will refactor to 

```
print("control");
```

So, the flag specific behavior needs to be specified in the build file to obtain the required refactoring.

**Comment by ketkarameya** [comment]
@aakriti-kedia I am closing this issue. Feel free to reopen it, if you have further questions.
